export const clientReviews = [
  {
    _id: "rev_1",
    customerName: "Ayesha Rahman",
    customerImage: "/images/customers/ayesha.jpg",
    profession: "University Student",
    rating: 5,
    comment: "Amazing experience! My hair feels soft and shiny. Staff were very professional.",
    date: "2025-09-10",
  },
  {
    _id: "rev_2",
    customerName: "Nusrat Jahan",
    customerImage: "/images/customers/nusrat.jpg",
    profession: "Bank Officer",
    rating: 4,
    comment: "Very relaxing pedicure. The environment was soothing. Could improve waiting time.",
    date: "2025-09-11",
  },
  {
    _id: "rev_3",
    customerName: "Mehedi Hasan",
    customerImage: "/images/customers/mehedi.jpg",
    profession: "Software Engineer",
    rating: 5,
    comment: "Best facial I’ve ever had. My skin feels fresh and glowing!",
    date: "2025-09-12",
  },
  {
    _id: "rev_4",
    customerName: "Rifat Akter",
    customerImage: "/images/customers/rifat.jpg",
    profession: "School Teacher",
    rating: 3,
    comment: "Service was good, but I expected more detailed consultation before treatment.",
    date: "2025-09-13",
  },
  {
    _id: "rev_5",
    customerName: "Tanvir Alam",
    customerImage: "/images/customers/tanvir.jpg",
    profession: "Businessman",
    rating: 4,
    comment: "Nice haircut, exactly as I wanted. Staff was friendly.",
    date: "2025-09-13",
  },
];
