export const services = [
  {
    _id: 1,
    name: "Face Wash",
    description: "Refreshing deep cleansing face wash for glowing skin.",
    category: "Facial",
    price: 500,
    discount: 5,
    duration: "30 min",
    image: "https://skinkraft.com/cdn/shop/articles/Facial-Versus-Clean-up_1024x400.jpg?v=1593155930",
    rating: 4.6,
    totalOrder: 210,
    products: ["Herbal Cleanser", "Aloe Vera Gel"],
    benefits: ["Removes dirt & oil", "Prevents acne", "Gives instant freshness"],
    availableStaff: ["Anika", "Mithila"],
    slots: ["9:00 AM", "10:30 AM", "1:00 PM", "4:00 PM"],
    preparation: "Avoid heavy makeup before appointment.",
    status: "active"
  },
  {
    _id: 2,
    name: "Skin Treatment",
    description: "Advanced treatment for clear, radiant, and healthy skin.",
    category: "Skin",
    price: 1500,
    discount: 15,
    duration: "1 hr",
    image: "https://sparshskinent.com/wp-content/uploads/2024/09/bridal-treatment.jpg",
    rating: 4.9,
    totalOrder: 120,
    products: ["Vitamin C Serum", "Hydrating Mask", "Sunscreen"],
    benefits: ["Reduces dark spots", "Improves skin tone", "Hydrates deeply"],
    availableStaff: ["Sadia", "Lamia"],
    slots: ["11:00 AM", "1:00 PM", "3:30 PM", "6:00 PM"],
    preparation: "Do not apply cream/lotion before service.",
    status: "active"
  },
  {
    _id: 3,
    name: "Hair Spa",
    description: "Nourishing hair spa for shiny and strong hair.",
    category: "Hair",
    price: 1200,
    discount: 10,
    duration: "45 min",
    image: "https://media.istockphoto.com/id/492625629/photo/in-the-barbershop.jpg?s=612x612&w=0&k=20&c=n_-H9J5d3NnClMRWv5S_mKGK_8fadkzRQ83mGQarZC8=",
    rating: 4.8,
    totalOrder: 152,
    products: ["L’Oréal Hair Mask", "Organic Herbal Oil", "Keratin Serum"],
    benefits: ["Reduces hair fall", "Boosts shine & softness", "Relieves stress with head massage"],
    availableStaff: ["Sadia", "Anika"],
    slots: ["10:00 AM", "12:00 PM", "3:00 PM", "5:00 PM"],
    preparation: "Please wash your hair before appointment.",
    status: "active"
  }
];
