export const teammates = [
  {
    id: 1,
    name: "Ayesha Rahman",
    age: 27,
    gender: "Female",
    experience: "4 years",
    expertIn: ["Hair Styling", "Bridal Makeup", "Hair Coloring"],
    rating: 4.8,
    availableDays: ["Monday", "Tuesday", "Thursday", "Saturday"],
    contact: "+8801789123456",
    photo:
      "https://img.freepik.com/free-photo/pretty-smiling-joyfully-female-with-fair-hair-dressed-casually-looking-with-satisfaction_176420-15187.jpg?semt=ais_hybrid&w=740&q=80",
    bio: "Ayesha is a professional hair stylist and bridal artist known for her elegant and modern looks.",
    status: "Available",
  },
  {
    id: 2,
    name: "Nusrat Jahan",
    age: 25,
    gender: "Female",
    experience: "3 years",
    expertIn: ["Facial", "Skin Treatment", "Waxing"],
    rating: 4.6,
    availableDays: ["Sunday", "Tuesday", "Friday"],
    contact: "+8801798123487",
    photo:
      "https://media.istockphoto.com/id/1297633362/photo/her-beauty-makes-it-hard-not-to-stare.jpg?s=612x612&w=0&k=20&c=_9EUpPSnGGbnkD-Ejfa-wTcso_ET10QQhpgglHcyUyM=",
    bio: "Nusrat specializes in skin care and facial treatments, ensuring a glowing and healthy skin for clients.",
    status: "Available",
  },
  {
    id: 3,
    name: "Sadia Akter",
    age: 30,
    gender: "Female",
    experience: "7 years",
    expertIn: ["Bridal Makeup", "Makeover", "Eye Makeup"],
    rating: 4.9,
    availableDays: ["Wednesday", "Thursday", "Friday"],
    contact: "+8801755123421",
    photo:
      "https://www.drmalaymehta.com/wp-content/uploads/2023/12/female-baldness-treatment_mumbai.jpg",
    bio: "Sadia is a certified makeup artist with years of bridal and event makeup experience.",
    status: "Busy",
  },
  {
    id: 4,
    name: "Rafiul Hasan",
    age: 29,
    gender: "Male",
    experience: "5 years",
    expertIn: ["Hair Cutting", "Beard Styling", "Hair Spa"],
    rating: 4.7,
    availableDays: ["Monday", "Wednesday", "Friday", "Sunday"],
    contact: "+8801711123456",
    photo: "https://plus.unsplash.com/premium_photo-1682096259050-361e2989706d?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8eW91bmclMjBtYW58ZW58MHx8MHx8fDA%3D",
    bio: "Rafiul is known for his trendy haircuts and beard styles that suit all face types.",
    status: "Available",
  },
  {
    id: 5,
    name: "Mehjabin Chowdhury",
    age: 26,
    gender: "Female",
    experience: "4 years",
    expertIn: ["Body Massage", "Spa Therapy", "Aromatherapy"],
    rating: 4.8,
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    contact: "+8801799123490",
    photo:
      "https://media.istockphoto.com/id/1478440723/photo/black-woman-arms-crossed-and-standing-in-confidence-with-vision-isolated-against-a-gray.jpg?s=612x612&w=0&k=20&c=cd4SdG1qNIxP9potasQ1jfzD9VbSbdkCqOtQtBmIT_0=",
    bio: "Mehjabin provides relaxing spa and massage services designed to reduce stress and rejuvenate the body.",
    status: "Available",
  },
  {
    id: 6,
    name: "Hasibul Islam",
    age: 31,
    gender: "Male",
    experience: "8 years",
    expertIn: ["Hair Treatment", "Hair Coloring", "Scalp Therapy"],
    rating: 4.9,
    availableDays: ["Monday", "Thursday", "Saturday"],
    contact: "+8801723123450",
    photo: "https://t4.ftcdn.net/jpg/02/14/74/61/360_F_214746128_31JkeaP6rU0NzzzdFC4khGkmqc8noe6h.jpg",
    bio: "Hasibul is a senior hair expert focusing on advanced hair treatment and care solutions.",
    status: "On Leave",
  },
];
